language: minimal

before_install:
  - wget https://github.com/vlang/v/archive/master.zip
  - unzip master.zip
  - cd v-master
  - make
  - cd ..
  - chmod +x merge.sh
  - ./merge.sh

script:
  - v-master/v popgenerator.v
